on:
  push:
   branches:
    - 'main'
    - 'master'
jobs:
  execute-scan-workflow:
    uses: threatrix/threat-agent-scan/.github/workflows/scan-repo-reusable.yaml@master
    with:
      eid: b0b3a923-6bb5-4053-9881-64a431294f52
      oid: 899c9b63-75fe-482c-aa31-e652d85e22e3
      app-name: threat-matrix-2-alisa
      trx-host: https://stage.threatrix.io
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      THREATRIX_SERVER_API_KEY: ${{ secrets.THREATRIX_API_KEY }}
